services:
  # 后端服务
  track-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: project-track-backend
    restart: unless-stopped
    privileged: true
    environment:
      - SERVER_PORT=:8082
      - DB_HOST=172.17.7.180
      - DB_PORT=3307
      - DB_USER=project_track
      - DB_PASSWORD=project_track_password
      - DB_NAME=project_track
      - UPLOAD_PATH=/app/uploads
      - JWT_SECRET=${JWT_SECRET:-project-flow-secret-key-2024}
      - TZ=Asia/Shanghai
    volumes:
      # 持久化上传文件
      - ./data/uploads:/app/uploads
    networks:
      - project-track-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/api/health"]
      interval: 20s
      timeout: 10s
      retries: 6
      start_period: 60s
    depends_on:
       track-mysql:
         condition: service_healthy
    ports:
      - "8082:8082"

  # 数据库服务（MySQL）
  track-mysql:
    #image: mysql:8.0
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/mysql:8.0.43
    container_name: project-track-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=project_track
      - MYSQL_USER=project_track
      - MYSQL_PASSWORD=project_track_password
      - TZ=Asia/Shanghai
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--max-connections=200"
    ]
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - project-track-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "3307:3306"

  # 前端服务
  track-frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: project-track-frontend
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8083}:80"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      track-backend:
        condition: service_healthy
    networks:
      - project-track-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  project-track-network:
    driver: bridge

volumes:
  db-data:
  upload-data:
